version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: Postgres555
  api:
    ports:
      - "5000:5000"
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
  client:
    networks:
    hfnet:
      ipv4_address: 127.0.0.1
    ports:
      - "8080:8080"
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
